name: Development

on:
  push:
    branches: ['main', 'release/*']
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ref:
        - develop
        - releases/v0.21
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Set up Spack
      uses: ./
      with:
        ref: ${{ matrix.ref }}
        buildcache: true
        color: true
    - name: Version check
      run: spack --version
    - name: Check build cache config
      run: spack config blame mirrors
    - name: Check build cache install in active env with spack-bash shell
      shell: spack-bash {0}
      run: |
        spack env activate
        spack install --add --cache-only --no-check-signature --reuse python
        which python3
        python3 -c 'print("hello world")'
    - name: Check spack-sh shell
      shell: spack-sh {0}
      run: |
        spack env activate
        spack env status