name: Development

on:
  push:
    branches: ['main', 'release/*']
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ref:
        - develop
        - releases/v0.21
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Set up Spack
      uses: ./
      with:
        ref: ${{ matrix.ref }}
        buildcache: true
        color: true
    - run: spack --version
    - name: Check if config is correct
      run: spack config blame mirrors
    - name: Test install from build cache
      run: spack install --reuse --no-check-signature --cache-only python
    - name: Check if spack-bash shell works
      run: |
        spack env activate
        spack env status
      shell: spack-bash
